version: '3.8'
services:
  mysql-container:
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
      MYSQL_DATABASE: dev_db
    ports:
       - "3307:3306" # Thay vì 3306:3306, dùng 3307 trên host



  springboot-app:
    ports:
      - "8080:8080" # Mở port ứng dụng
      - "5005:5005" # Port debug JDWP
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/dev_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dev_password
      - SPRING_PROFILES_ACTIVE=dev # Profile Spring Boot cho dev
    volumes:
      - ./target/tiendev.war:/app/app.war # Mount file WAR để reload nhanh (nếu cần)
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.war"] # Enable debug