version: '3.8'
services:
  mysql-container:
    environment:
      MYSQL_ROOT_PASSWORD: strong_prod_password
      MYSQL_DATABASE: prod_db
    # Không mở port 3306 ra ngoài, chỉ giao tiếp nội bộ

  springboot-app:
    ports:
      - "8080:8080" # Chỉ mở port ứng dụng
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/prod_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=strong_prod_password
      - SPRING_PROFILES_ACTIVE=prod # Profile Spring Boot cho prod
    deploy:
      replicas: 2 # Chạy 2 instance cho HA (nếu cần)
      resources:
        limits:
          cpus: "0.5"
          memory: 512M # Giới hạn tài nguyên